### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by flamby** [fmohr/AILibs#24]
Hello,

After having read the published paper "ML-Plan: Automated machine learning via hierarchical planning", this project appears very interesting. It's always interesting to have other approaches in auto ML as TPOT and auto-ML are the only way to go right now.

Is there any documentation, notably on how to build it?
I can't see any doc in this repo or the former one.

Thanks in advance

**Comment by mwever** [comment]
Hello flamby,

first of all thank you very much for your interest in our paper and project.
We are currently working at full speed on releasing executable jar binaries to make ML-Plan easily accessible.

We already started with a preliminary, sketchy readme file, explaining on how to build the project structure to be imported in eclipse.

I will let you know when we have released the first binary files that can be executed easily from the command line.

**Comment by fmohr** [comment]
So this issue has been posted already quite a while ago. Meanwhile, we have a substantially revised version of ML-Plan that is also published on Maven and should work out of the box.

You can find a short guide on how to use it here: https://github.com/fmohr/AILibs/tree/master/softwareconfiguration/mlplan

Is this helpful?

Best,
Felix

**Comment by fmohr** [comment]
I close the issue since there has been no reply in over three weeks.
