### ISSUE TITLE
MLPlan doesn't seem to start in some cases

### ISSUE THREAD

**Issue by mirkojuergens** [fmohr/AILibs#84]
I used the OpenML datasetid 3 with timeout 300, seed 1 and NodeEvaluationTimeout 60 with code that was copied from the MlPlanOpenMLExample
[console.log](https://github.com/fmohr/AILibs/files/2941581/console.log)

**Comment by fmohr** [comment]
Hi, this is not an issue but only a matter of log configuration. The printed lines at the end clearly indicate that ML-Plan has started to conduct evaluations. Maybe you want to set the log level to DEBUG instead of INFO if you want to be informed about current statistics.
