### ISSUE TITLE
MLPlan doesn't return a solution in some cases

### ISSUE THREAD

**Issue by mirkojuergens** [fmohr/AILibs#85]
I used the OpenML datasetid 3 with timeout 300, seed 1 and NodeEvaluationTimeout 60 with code that was copied from the MlPlanOpenMLExample
[console_2.log](https://github.com/fmohr/AILibs/files/2941639/console_2.log)

After that log MlPlan is just ideling and not reporting any solution.

**Comment by fmohr** [comment]
I think the issue should have been solved. Can you try again with a fresh copy of the `dev` and report whether the problem remains?
